require_relative "../app/game_class.rb"
require_relative "../app/user_class.rb"
require_relative "../app/hangman_art.rb"
require_relative "../app/random_words.rb"
require_relative "../app/get_user_input.rb"
require_relative "../bin/run.rb"
