require_relative "../app/game.rb"
require_relative "../app/user.rb"
require_relative "../app/hangmanart.rb"
require_relative "../app/randomwords.rb"
require_relative "../app/runner_questions.rb"
require_relative "../app/welcome.rb"